services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: guessdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    environment:
      FLASK_DB_TYPE: postgres
      FLASK_DB_NAME: guessdb
      FLASK_DB_USER: postgres
      FLASK_DB_PASSWORD: postgres
      FLASK_DB_HOST: db  
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
