apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: guess-game

spec:
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.frontend.nodePort }}

  type: NodePort